- src/main/scala/shell/xilinx/VC707Shell.scala
- xilinx/vc707/constraints/vc707-master.xdc
This corresponds to rocket-chip https://github.com/freechipsproject/rocket-chip/pull/975.
I believe that there are some constraints which may need to be updated in this PR as well.
> synchronizers: Use new primitives

- xilinx/common/tcl/prologue.tcl
Use a file instead of environment variable to pass VSRCS into Vivado
> Use a file instead of environment variable to pass VSRCS into Vivado

- src/main/scala/shell/xilinx/ArtyShell.scala
This goes along with https://github.com/sifive/sifive-blocks/pull/39
> signal_bundles: Use the new way as .fromPorts is gone

- xilinx/common/tcl/init.tcl
- xilinx/common/tcl/prologue.tcl
- xilinx/common/tcl/vivado.tcl
I've made a few changes that make it easier to run the Vivado Tcl scripts in a larger project. Main changes made:
Previously we had to pass several different scripts in the correct order to Vivado. In this PR vivado.tcl is now the entrypoint for all the Vivado Tcl scripts and will automatically source all the other required scripts. It will even source the correct `board` script via the `-board` command line argument.
A command line argument parser was written and replaces the previous system of using environment variables to pass values into the scripts. This makes it clearer where options come from and makes it harder to accidentally mix up environment variables when working on different projects.
The `VSRCSVIVADOTCL` environment variable has been replaced with a `-F` command line …
> Restructure Tcl script entrypoint.

- src/main/scala/devices/xilinx/xilinxvc707pciex1/XilinxVC707PCIeX1.scala
- src/main/scala/shell/xilinx/VC707Shell.scala
- xilinx/vc707/constraints/vc707-master.xdc
For Shell IO, use the bundles directly from PCIe and MIG IPs instead of flattening and renaming
> VC707 use IP IO bundles

- src/main/scala/devices/xilinx/xilinxvc707mig/XilinxVC707MIG.scala
- src/main/scala/ip/xilinx/vc707axi_to_pcie_x1/vc707axi_to_pcie_x1.scala
Capping TransferSizes at 128 fits nicely in 3 size bits.
> TransferSizes: just because a device CAN do more does not mean it should

- xilinx/common/tcl/prologue.tcl
- xilinx/vc707/constraints/vc707-master.tcl
- xilinx/vc707/constraints/vc707-master.xdc
This is needed because sometimes PCIe/DDR/CL/etc are disabled. In those cases we still need to cut the remaining clock groups.
> Dynamic clock groups

- src/main/scala/devices/xilinx/xilinxvc707mig/XilinxVC707MIG.scala
- src/main/scala/devices/xilinx/xilinxvc707mig/XilinxVC707MIGPeriphery.scala
- src/main/scala/devices/xilinx/xilinxvc707pciex1/XilinxVC707PCIeX1.scala
- src/main/scala/devices/xilinx/xilinxvc707pciex1/XilinxVC707PCIeX1Periphery.scala
keep up to date with changes to buswrapper API in rocket-chip
> periphery: bus api update

- src/main/scala/devices/xilinx/xilinxvc707pciex1/XilinxVC707PCIeX1.scala
Changing AXI4 to support denied requires AXI4Lite adapters to change TLFragmenter options.
> VC707PCIe: adapt to AXI4Lite API change

- src/main/scala/ip/microsemi/polarfire_pcie_rootport/PolarFirePCIeRootPort.scala
- src/main/scala/ip/xilinx/vc707axi_to_pcie_x1/vc707axi_to_pcie_x1.scala
Scala 2.12's type checker is more thorough than 2.11's. This PR suppresses "match may not be exhaustive" warnings.
> Make 2.12 type checker happy

- src/main/scala/shell/xilinx/VC707Shell.scala
- xilinx/vc707/tcl/clocks.tcl
- xilinx/vc707/tcl/ios.tcl
The TCL hooks were in the wrong place.
> VC707: fix legacy Shell

- src/main/scala/shell/ChipLinkOverlay.scala
- src/main/scala/shell/LEDOverlay.scala
- src/main/scala/shell/SwitchOverlay.scala
- src/main/scala/shell/microsemi/PolarFireEvalKitShell.scala
- src/main/scala/shell/microsemi/VeraShell.scala
- src/main/scala/shell/xilinx/LEDOverlay.scala
- src/main/scala/shell/xilinx/VC707NewShell.scala
- src/main/scala/shell/xilinx/VC707Shell.scala
We removed the `BundleBridge` wrapper, so some shells now have to use the source and sink nodes directly. This adds the equivalent nodes in the overlay.
> BundleBridge: use source and sink nodes directly

- src/main/scala/ip/xilinx/xdma/xdma.scala
- src/main/scala/shell/PCIeOverlay.scala
- src/main/scala/shell/xilinx/VCU118NewShell.scala
- xilinx/vcu118/tcl/board.tcl
We cannot use the board description anymore, because vivado refuses to place a PCIe root complex on the edge connector.
> vcu118: make it possible to instantiate two PCIe interfaces at once

- src/main/scala/shell/xilinx/VC707NewShell.scala
While 4GB chips are possible, they should not be the default!
> VC707Shell: default to 1GB of RAM (what the board ships with)

- src/main/scala/shell/microsemi/PolarFireEvalKitShell.scala
- src/main/scala/shell/xilinx/ArtyShell.scala
- src/main/scala/shell/xilinx/VC707Shell.scala
- src/main/scala/shell/xilinx/VCU118Shell.scala
It's more future-proof to operate on the specific bundle and param instances required instead of expecting a specific trait of a specific hierarchy level.
Future work:
- eliminate further dependencies on similar traits (Debug (#41), XilinxMIG)
- standardize dut_clock and dut_reset so they're always available, or some other way to make sure that the right clock is used for each peripheral's connection wiring
> connectSPI and connectUART no longer require entire dut

- src/main/scala/shell/xilinx/VC707NewShell.scala
Put JTAG for VC707 on the LCD connector, instead of an add-on board.
needs review for conflicts and testing of what happens if the LCD is installed.
> Move JTAG to LCD connector

- src/main/scala/shell/xilinx/ArtyShell.scala
- xilinx/arty/constraints/arty-master.xdc
- xilinx/arty_a7_100/constraints/arty-master.xdc
Changes to expose pins on Arty PMOD header JC for use by trace encoder and external triggers.  This PMOD was chosen because of its proximity to the debug connections on JD - at least one trace probe vendor has suggested making an adapter board to go between their probe and JC/JD.
> Expose JC for trace I/O

- src/main/scala/shell/xilinx/ArtyShell.scala
- src/main/scala/shell/xilinx/VC707NewShell.scala
- xilinx/vc707/constraints/vc707-master.xdc
- xilinx/vc707/vsrc/sdio.v
This change slipped away when I made the PR https://github.com/sifive/fpga-shells/pull/64.
This change is required for the PR https://github.com/sifive/freedom/pull/118 to avoid the following build error.
``` 
[error] /home/user/freedom/fpga-shells/src/main/scala/shell/xilinx/ArtyShell.scala:173:34: value sampleDelay is not a member of sifive.blocks.devices.spi.SPIFlashParams
[error] Error occurred in an application involving default arguments.
[error]         syncStages = qspi_params.sampleDelay
[error]                                  ^
[error] one error found
[error] (fpgaShells / Compile / compileIncremental) Compilation failed
```
> Revert "Revert "SPI speedup related FPGA changes""

- src/main/scala/shell/GPIOOverlay.scala
- src/main/scala/shell/I2COverlay.scala
- src/main/scala/shell/JTAGDebugOverlay.scala
- src/main/scala/shell/PWMOverlay.scala
- src/main/scala/shell/PinOverlay.scala
- src/main/scala/shell/SPIFlashOverlay.scala
- src/main/scala/shell/Shell.scala
- src/main/scala/shell/UARTOverlay.scala
- src/main/scala/shell/xilinx/Arty100TShell.scala
- src/main/scala/shell/xilinx/GPIOXilinxOverlay.scala
- src/main/scala/shell/xilinx/I2COverlay.scala
- src/main/scala/shell/xilinx/JTAGDebugOverlay.scala
- src/main/scala/shell/xilinx/PWMOverlay.scala
- src/main/scala/shell/xilinx/PinXilinxOverlay.scala
- src/main/scala/shell/xilinx/SPIFlashXilinxOverlay.scala
- src/main/scala/shell/xilinx/UARTOverlay.scala
- src/main/scala/shell/xilinx/VCU118NewShell.scala
Change many overlay IO types to Analog and Vec in some cases. Move top-level io connectivity to subclasses to allow for use in ASIC designs
> Overlays: Analog, change top-level io connectivity

- src/main/scala/shell/DDROverlay.scala
- src/main/scala/shell/xilinx/VC707NewShell.scala
allow choice of 1gb/4gb dimm based on size field of overlay (vc707 only for now, not sure if this should be for other boards at all)
> Vc707 1 4gb config

- src/main/scala/shell/xilinx/Arty100TShell.scala
TMSC can't have both PULLUP and KEEPER, this removes pullup from it
> no pullup on keeper pin

- src/main/scala/shell/xilinx/ArtyShell.scala
- src/main/scala/shell/xilinx/VC707Shell.scala
- src/main/scala/shell/xilinx/VCU118Shell.scala
Goes with https://github.com/chipsalliance/rocket-chip/pull/2155: The Debug Module and DebugIO are now options.  Also drive the new part_number and version fields of IDCODE.
> Debug: Make Debug Module optional

- src/main/scala/shell/xilinx/XilinxShell.scala
Add a way to include a generated extra xdc file into the vivado build, if it exists. Like it says in the comment, this is a bit of a hack in order to get stuff building, the long term solution is to make an overlay with no IOs or bundlebridges that literally just adds xdc constraints, but we currently dont have the ability to easily add the needed constraints, so I decided on this method now, assuming that either I or @albavince will revert this once the other path is ready.
> Add extra xdc

- xilinx/common/tcl/prologue.tcl
tcl didnt like this, so I am removing it. The comment below it still describes the function though
> removing inline tc comment

- src/main/scala/shell/I2COverlay.scala
- src/main/scala/shell/PWMOverlay.scala
- src/main/scala/shell/SPIFlashOverlay.scala
- src/main/scala/shell/UARTOverlay.scala
- src/main/scala/shell/xilinx/PWMOverlay.scala
- src/main/scala/shell/xilinx/PeripheralsVC707Shell.scala
- src/main/scala/shell/xilinx/VC707NewShell.scala
- wit-manifest.json
- xilinx/common/vsrc/AnalogToUInt.v
- xilinx/common/vsrc/UIntToAnalog.v
Make a VC707 shell with peripheral overlays, move UART up a level so that it is not part of the lowest level shell (since it is a peripheral), but still is included in builds using VC707BaseShell
> Peripherals shell

- src/main/scala/shell/JTAGDebugOverlay.scala
- src/main/scala/shell/cJTAGDebugOverlay.scala
- src/main/scala/shell/xilinx/Arty100TShell.scala
- src/main/scala/shell/xilinx/JTAGDebugOverlay.scala
The srst_n input is an input signal with a pullup.  An external probe can drive this low to request a system reset.
> Restore jtag/cjtag srst_n input so external probes can reset the system

- src/main/scala/shell/xilinx/VCU118NewShell.scala
VCU118 spirit flash requires startupe3 to operate post programming – not yet onboarded
> remove spi flash

- src/main/scala/devices/microsemi/polarfire_pcie/PolarFireEvalKitPCIeX4.scala
fix this Chisel compile warning:
```
[warn] /federation/fpga-shells/src/main/scala/devices/microsemi/polarfire_pcie/PolarFireEvalKitPCIeX4.scala:62:33: method apply in object IntSyncCrossingSink is deprecated (since rocket-chip 1.2): IntSyncCrossingSink which used the `sync` parameter to determine crossing type is deprecated. Use IntSyncAsyncCrossingSink, IntSyncRationalCrossingSink, or IntSyncSyncCrossingSink instead for > 1, 1, and 0 sync values respectively
[warn]   val intnode: IntOutwardNode = IntSyncCrossingSink() := TLScope {
[warn]                                 ^
```
- Paying Off Technical Debt
> Chisel compile warning: deprecated IntSyncCrossingSink

- src/main/scala/shell/xilinx/VC707NewShell.scala
This PR applies a location constraint and pullup to the srst_n input in VC707 builds.  I know VC707 is not officially supported any more, but some engineers still have them and it's useful to be able to do internal builds targeted at VC707.  Before this change, Vivado would error out because this I/O is in the design but it doesn't have a location constraint.
With this change, I was able to successfully build standard core U77 for VC707 using PCS.
> Locate IO srst_n to proper pin on LCD connector

- src/main/scala/shell/GPIOOverlay.scala
- src/main/scala/shell/I2COverlay.scala
- src/main/scala/shell/IOShell.scala
- src/main/scala/shell/JTAGDebugOverlay.scala
- src/main/scala/shell/PWMOverlay.scala
- src/main/scala/shell/SPIFlashOverlay.scala
- src/main/scala/shell/UARTOverlay.scala
background: At the request of the physical implementation & design team,
we needed a space to put the pad in one place.
So I created a value called padPlace.
padPlace default value is shell.
Add def padPlace: LazyScope = shell in IOPlacedOverlay trait
Changed the existing sink scope from shell to padPlace.
in GPIOPlacedOverlay, I2CPlacedOverlay, JTAGDebugPlacedOverlay,
PWMPlacedOverlay, SPIFlashPlacedOverlay, UARTPlacedOverlay
> Add padPlace: LazyScope value

- src/main/scala/ip/xilinx/xdma/xdma.scala
- src/main/scala/shell/PCIeOverlay.scala
- src/main/scala/shell/xilinx/VCU118NewShell.scala
This is necessary to support PCIe controllers without access to physical
addresses below 4GiB. The kernel appears to happily map even 32-bit device
BARs to high 64-bit base-addresses for the RC BARs.
> xdma: support BARs with physical address != PCIe address

- xilinx/common/tcl/prologue.tcl
For some reason, the previous code was always returning 0 (even after adding the upvar). When refactored this way, it works again
> refactor tcl code that wasn't executing correctly

- src/main/scala/shell/PCIeOverlay.scala
- src/main/scala/shell/xilinx/VCU118NewShell.scala
Hi teams,
I've created the class to re-locate the JTAG pinouts to J53 on VCU118 in order to we can use SD card on J52 and use JTAG on J53 simultaneously.
And the same time, I also create the PCIeFMCOverlayKey and PCIeEdgeOverlayKey in PCIeOverlayKey.scala. So we can use them to allocate independent Xilinx XDMA PCIe IP on different interface. It provides more feasible if we need PCIe interface.
Thanks for reviewing them and give me some feedback if you have any questions.
Regards,
Jacka
> PMOD2 and PCIe key on vcu118 new shell

- src/main/scala/devices/microsemi/polarfire_ddr3/MicrosemiPolarFireDDR3.scala
- src/main/scala/devices/microsemi/polarfire_ddr4/MicrosemiPolarFireDDR4.scala
- src/main/scala/devices/xilinx/xilinxvc707mig/XilinxVC707MIG.scala
- src/main/scala/devices/xilinx/xilinxvcu118mig/XilinxVCU118MIG.scala
This parameter was deemed to be inevitably harmful to performance in certain situations and has been deprecated.
> DDR controllers: do not use deprecated stripBits parameter of TLToAXI4

- src/main/scala/shell/xilinx/XilinxShell.scala
Small change to set the IBUF_LOW_POWER property for an `IOPin`
> Add Xilinx IBUF_LOW_POWER property
