src/main/scala/ip/xilinx/Xilinx.scala, src/main/scala/shell/xilinx/VC707Shell.scala, xilinx/vc707/constraints/vc707-master.xdc
Also add MMCM to provide 65Mhz (and multiples) clock
=> VC707 Shell : Make DDR and PCIe optional, mixed into Shell with traits

src/main/scala/shell/xilinx/VC707Shell.scala
This is needed to push the FPGA design into freedom
=> chiplink: add pinout

src/main/scala/devices/xilinx/xilinxvc707mig/XilinxVC707MIG.scala, src/main/scala/ip/xilinx/Xilinx.scala
A few non-controversial changes, moved out of my larger design/shell PR.
=> Make MIG clocking internal and clean-up MMCM code style

xilinx/arty-a7-100/constraints/arty-config.xdc, xilinx/arty-a7-100/constraints/arty-master.xdc, xilinx/arty-a7-100/tcl/board.tcl, xilinx/arty-a7-100/tcl/ip.tcl, xilinx/common/tcl/boards.tcl
Copied the arty directory and modified the board info alone.
=> Added arty-a7-100 board

src/main/scala/devices/microsemi/polarfire_ddr3/MicrosemiPolarFireDDR3Periphery.scala, src/main/scala/devices/microsemi/polarfire_ddr4/MicrosemiPolarFireDDR4Periphery.scala, src/main/scala/devices/xilinx/xilinxvc707mig/XilinxVC707MIGPeriphery.scala, src/main/scala/devices/xilinx/xilinxvcu118mig/XilinxVCU118MIGPeriphery.scala
This removes a lot of require checks!
=> mbus: switch to multi-bank API

src/main/scala/shell/xilinx/ArtyShell.scala, xilinx/vc707/constraints/vc707-master.xdc, xilinx/vc707/vsrc/sdio.v
=> Fpga spi speedup

src/main/scala/shell/xilinx/ArtyShell.scala, xilinx/vc707/constraints/vc707-master.xdc, xilinx/vc707/vsrc/sdio.v
Reverts sifive/fpga-shells#43
The corresponding sifive-blocks change needs additional testing
=> Revert "Fpga spi speedup"

src/main/scala/ip/xilinx/xdma/xdma.scala, xilinx/common/tcl/vivado.tcl
Previously the ECAM had to be at 4GB boundaries.
=> XDMA: support ECAM at any legal multiple

src/main/scala/shell/xilinx/VCU118NewShell.scala, xilinx/common/tcl/prologue.tcl, xilinx/common/tcl/vivado.tcl
Layer VCU118 shell above VCU118ShellBasicOverlays
=> Layer VCU118 shell above VCU118ShellBasicOverlays

src/main/scala/shell/SPIFlashOverlay.scala, src/main/scala/shell/xilinx/Arty100TShell.scala, src/main/scala/shell/xilinx/SPIFlashXilinxOverlay.scala, src/main/scala/shell/xilinx/VCU118NewShell.scala
Enabling qspi on newshell designs
=> Qspi newshell

src/main/scala/devices/xilinx/xilinxarty100tmig/XilinxArty100TMIG.scala, src/main/scala/shell/ButtonOverlay.scala, src/main/scala/shell/GPIOPMODOverlay.scala, src/main/scala/shell/SPIFlashOverlay.scala, src/main/scala/shell/Shell.scala, src/main/scala/shell/Util.scala, src/main/scala/shell/xilinx/Arty100TShell.scala, src/main/scala/shell/xilinx/ButtonOverlay.scala, src/main/scala/shell/xilinx/GPIOPMODXilinxOverlay.scala
Added overlay for gpio pmods. Originally I had the connections in the overlay but figured this would be better off in the design because it would be easier to control the connections. I've left that part commented but will remove once people take a look.
=> Gpio pmod overlay

src/main/scala/shell/xilinx/VC707Shell.scala
=> Add tactical String concats to avoid Scala compiler stack overflow

src/main/scala/shell/TracePMODOverlay.scala, src/main/scala/shell/xilinx/Arty100TShell.scala, src/main/scala/shell/xilinx/TracePMODOverlay.scala
Assign PMODC pins for trace functions.
=> Trace newshells

src/main/scala/shell/xilinx/VC707NewShell.scala, src/main/scala/shell/xilinx/VC707Shell.scala, xilinx/vc707/constraints/vc707-master.xdc, xilinx/vc707/vsrc/sdio.v
This pull request is prerequisite for the top pull request of freedom for vc707 with and without PCIe-HMC board as disccusted at #116
=> Vc707 nopcie switchable

src/main/scala/shell/xilinx/VC707NewShell.scala
This is PR against master of https://github.com/sifive/fpga-shells/pull/80
=> Fix vc707+FMC-PCIe do not work after 6094008

src/main/scala/clocks/ClockGroup.scala, src/main/scala/clocks/Nodes.scala, src/main/scala/clocks/PLLFactory.scala, src/main/scala/clocks/Parameters.scala, src/main/scala/ip/xilinx/Xilinx.scala, src/main/scala/shell/ChipLinkOverlay.scala, src/main/scala/shell/Ethernet.scala, src/main/scala/shell/IOShell.scala, src/main/scala/shell/microsemi/ChipLinkOverlay.scala, src/main/scala/shell/microsemi/VeraShell.scala, src/main/scala/shell/xilinx/Arty100TShell.scala, src/main/scala/shell/xilinx/ChipLinkOverlay.scala, src/main/scala/shell/xilinx/UltraScaleShell.scala, src/main/scala/shell/xilinx/VC707NewShell.scala, src/main/scala/shell/xilinx/VCU118NewShell.scala
Revert changes that broke SDC flow,
=> Sdc fix rebase

xilinx/common/tcl/prologue.tcl
Redone tcl reading from environment variable
=> Tcl env var

src/main/scala/shell/GPIOOverlay.scala, src/main/scala/shell/I2COverlay.scala, src/main/scala/shell/PWMOverlay.scala, src/main/scala/shell/SPIFlashOverlay.scala, src/main/scala/shell/UARTOverlay.scala
Also cleaned up a bunch of code formatting
=> Add ObjectModel support for peripheral overlays

src/main/scala/shell/Util.scala
fixing name of the blackbox module
=> fix name generation

src/main/scala/shell/Util.scala
Reverts sifive/fpga-shells#113
=> Revert "fix name generation"

src/main/scala/shell/Util.scala
give desirednames to blackboxes
=> name the bbs correctly

src/main/scala/shell/xilinx/VCU118NewShell.scala
commit I forgot, adds buttons to vcu118 and moves jtag to the pod by default
=> add buttons and put jtag on pmod default

src/main/scala/devices/xilinx/ethernet/ethernet.scala, src/main/scala/ip/xilinx/xxv_ethernet/nfmac10g.scala, src/main/scala/ip/xilinx/xxv_ethernet/xxv_ethernet.scala, src/main/scala/shell/Ethernet.scala
My guess is none of this code was in regression.
=> ethernet: clarify which kind of resets are used

src/main/scala/shell/JTAGDebugOverlay.scala, src/main/scala/shell/xilinx/VCU118NewShell.scala
baremetal shell has jtag on female PMOD for sifive adapter board
Linux shell has jtag on fmc so that sdio can occupy pmod
=> separate baremetal shell and linux shell

src/main/scala/shell/cJTAGDebugOverlay.scala, src/main/scala/shell/xilinx/VCU118NewShell.scala
Add cjtag overlay, fix some firrtl-related cjtag stuff
May need to make it more conditional since it is only on PMOD now, but this at least makes it reachable
=> cjtag on vcu118

src/main/scala/shell/xilinx/VCU118NewShell.scala
PMOD has issues with level shifters... Move to FMC1 (J2) J20 P1-3 instead
=> move cjtag to vcu118 fmc

src/main/scala/shell/JTAGDebugOverlay.scala, src/main/scala/shell/cJTAGDebugOverlay.scala, src/main/scala/shell/xilinx/Arty100TShell.scala
Cherry-pick of #105 from master to rg1908
=> Restore s_rst_n connection

src/main/scala/shell/xilinx/JTAGDebugBScanOverlay.scala
#103 introduce a bug which didn't import bscan, this PR fix this issue.
So sorry for that!
=> bug fix for #103

src/main/scala/ip/xilinx/bscan/bscan.scala, src/main/scala/shell/xilinx/VCU118NewShell.scala
Sorry, I'm constructing hardware CI.
and notice there was a bug in bscan tunnel(my fault).
=> fix bscan again

.github/workflows/test.yml, wit-manifest.json
Had to bump nearly every wit dependency as part of this PR.
=> CI: add a scala compilation check

src/main/scala/shell/xilinx/XilinxShell.scala
Small change to modify the drive strength for an `IOPin`.
=> Add Xilinx drive strength property

wit-manifest.json
bump latest sifive-blocks for GPIO function mux changes
=> bump sifive-blocks
